### ISSUE TITLE
Fails with zsh

### ISSUE THREAD

**Issue by kergoth** [garmin/pyrex#31]
When attempting to source pyrex-init-build-env from zsh:
```
Traceback (most recent call last):
  File ".../pyrex/pyrex.py", line 610, in <module>
    main()
  File ".../pyrex/pyrex.py", line 606, in main
    sys.exit(args.func(args))
  File ".../pyrex/pyrex.py", line 231, in capture
    os.write(args.fd, build_conffile.encode('utf-8'))
OSError: [Errno 9] Bad file descriptor
```

It seems that use of file descriptors greater than 10 without using the `{varname}` syntax is not particularly portable among shells. See also https://unix.stackexchange.com/a/227100. Use of 0-9 seems to be more portable.

**Comment by kergoth** [comment]
Verified that using fd 9 instead of 11 works for zsh.
